--- #YAML:1.0
name:               R-Comment2DocDraft
version:            0.1
abstract:           convert comments to documentaries in R script
author:
    - Zuguang Gu <jokergoo@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    English:     0
    File::Temp:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
